### ISSUE TITLE
deploy pgweb as a container alongside postgres in a docker-compose setup?

### ISSUE THREAD

**Issue by zfrenchee** [sosedoff/pgweb#216]
Hello!
This looks terrific. For my use case, I'd love to run this container alongside my postgres container, link them together, and have pgweb available at some port on my URL. Is that an idea that's been had before?

**Comment by zfrenchee** [comment]
My mistake, I didn't look closely at the wiki! 
https://github.com/sosedoff/pgweb/wiki/Docker
This mostly answers my question. I'll try to figure the rest out on my own.

**Comment by zfrenchee** [comment]
Okay, so I added to my docker-compose file the following: 

```
pgweb:
  container_name: pgweb
  restart: always
  image: sosedoff/pgweb
  ports: 
    - "8081:8081" 
  links: 
    - postgres:postgres
  environment:
    - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
```

I have my functional postgres db in the same file

With the above, I get: 
```
Connecting to server...
Error: dial tcp: lookup db on 192.168.65.1:53: no such host
```

If I change the environment line to 
```
    - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres

```
I get
```
Connecting to server...
Error: dial tcp 172.17.0.2:5432: getsockopt: connection refused
```
I changed the name just in case since my image is called postgres not db, the way you name it on the wiki https://github.com/sosedoff/pgweb/wiki/Docker

Any ideas?

**Comment by sosedoff** [comment]
As far as connecting to the postgres (from pgweb) it should just work as long as the postgres server is reachable and credentials are correct (host/port/user/db). From your example its not clear how you start postgres container. Could you provide more details from your compose file?

**Comment by zfrenchee** [comment]
Hi @sosedoff 
Here's the postgres piece of the compose file: 
```
postgres:
  container_name: postgres
  restart: always
  image: postgres:latest
  volumes:
    - ./postgres-data:/var/lib/postgresql/data
  ports:
    - "5432:5432"
```

**Comment by sosedoff** [comment]
Postgres does not start right away, it takes a few seconds after start to become fully available.
Since pgweb depends on the postgres container, you have to specify that in your compose file:

```
pgweb:
  container_name: pgweb
  restart: always
  image: sosedoff/pgweb
  ports: 
    - "8081:8081" 
  links: 
    - postgres:postgres
  environment:
    - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
  depends_on:
    - postgres
```

Also, default postgres container does not have SSL enabled, so just disable that. New variables:

```
DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
```
