### ISSUE TITLE
Bookmark server connections

### ISSUE THREAD

**Issue by sosedoff** [sosedoff/pgweb#70]
Another great addition to the pgweb could be "bookmarked" connections. This will provide a way to
quickly server connection settings. Most native database managers do that and its very helpful. 

Few options to consider:

**Store bookmarks in cookie/localstorage**
- Pros: easy implementations
- Cons: no real persistence

**Store bookmarks in a local file**

File could be something like `~/.pgweb_bookmarks`. Not sure about how would this work on
Windows machines. As for file format, it could be either YAML or TOML. Im leaning towards
TOML since it has format very similar to INI files. However, JSON does really make sense to use,
its consumed by browser but it does not have great readability. 
- Pros: opens doors for more customizations, easy implementation
- Cons: syntax/formatting

Proposed file format (TOML):

``` toml
# If url is defined it takes precedence
url = "postgres://..."

# Regular server connection settings
host = "localhost"
port = 5432
user = "username"
database = "dbname"
ssl_mode = "disable"
```

Would like to get some feedback if anyone is interested.
