### ISSUE TITLE
TLS Failure

### ISSUE THREAD

**Issue by gautada** [sosedoff/pgweb#705]
I am at my wits end and I am pretty sure this is not the correct forum but any directional help will be greatly appreciated.

## Environment:
I have pgweb running as container in a kubernetes pod. Full deployment  with ingress, services, etc.  

## Issue:
The deployment works fine with zero issues until I enable TLS in the ingress config. Once tis is turned on assets are not loaded.  The '/' is working so the html is downloaded.  Some assets (the CSS files) are downloaded by the client no problem but non of the JS files are downloaded.  The only difference is the TLS change in ingress:

ingress.yml:
```
...
spec:
  tls:
  - hosts:
      - fqdn.host.tld
  ingressClassName: public
  rules:
...
```

For debugging I have removed annotations in the ingress file

So when requesting https://fqdn.domain.tld/ in the browser any js asset fails to download.  The request returns NULL.  No HTTP response, no HTTP response code, just NULL.

## Debugging:

1. Everything works when not using the tis section in the ingress.yml (i.e. http://fqd.domain.tld).  This proves the deployment chain ingress->service->pod is working and the pgweb container is working just fine.
2. With TLS all asset paths are accessible. I can cURL all URLS (i.e. https://fqdn.domain.tld/, https://fqdn.domain.tld/static/css/*.css, https://fqdn.domain.tld/static/js/*.js) are all directly accessible.  
3. When requesting https://fqdn.domain.tld/ only the requests for `/` or `static/css/*.css` show up in the ingress log. It seems like the javascript requests are not in log.
4. Assuming this is some browser issue default is Safari, I ran in Firefox and Chrome.  Same issue in each browser. FAILED
5. Assuming this may be browser security setting I turned disabled Developer Settings...>Disable cross-origin restrictions FAILED.
6. I have attempted to adjust the <script>... tags in the index.html file of pgweb.  Tried:
   6.a: Changing the mime type to application/javascript ... x-javascript ...  etc.
   6.b: Changingthe path to an absolute path from static/js/*.js to /statis/js/*.js
   FAILED: Confirmed changes to html were deployed, again I get the HTML and CSS assets.
7. I tried every combination of enabling CORS both in the ingress through annotations and in the parameters of pgweb. FAILED

Finally,  I isolated the HTTP request and response using cURL from Debug Timeline in Safari.

```
curl 'https://fqdn.domain.tld/static/js/jquery.js' \
-X 'GET' \
-H 'Accept: */*' \
-H 'Referer: https://fqdn.domain.tld/' \
-H 'Sec-Fetch-Dest: script' \
-H 'Sec-Fetch-Mode: no-cors' \
-H 'Sec-Fetch-Site: same-origin' \
-H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15' 
```

This works but the call from the browser on <script> tag still fails.

I am happy to expose the dev environment temporarily to anyone wanting to see for themselves.

Any help towards a solution would be great.

**Comment by sosedoff** [comment]
Thanks for the report. 

I've run pgweb on k8s with tls before, so it's definitely doable. Do you have any scripts/configs to share so i can try to repro the issue?

**Comment by gautada** [comment]
OMG! That would be great.

The code for the container is:  https://github.com/gautada/pgweb-container
The image repo is: https://hub.docker.com/repository/docker/gautada/pgweb/general

The deployment.yml is

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgweb
  namespace: data
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: pgweb
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: pgweb
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node.gautier.org/layer
                operator: In
                values:
                - troposphere
      containers:
      - name: pgweb
        image: gautada/pgweb:test
        imagePullPolicy: Always
        env:
        - name: PGWEB_DATABASE_URL
          value: "postgres://pgweb@psql.gautier.org:5432/postgres?connect_timeout=30&sslmode=disable"
        # - name: PGWEB_CORS_ORIGIN  
        #   value: "http://pgweb.data.svc.cluster.local:8080/"
        livenessProbe:
          exec:
            command:
            - /usr/bin/container-liveness
          failureThreshold: 10
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          exec:
            command:
            - /usr/bin/container-readiness
          failureThreshold: 10
          initialDelaySeconds: 5
          periodSeconds: 5
        startupProbe:
          exec:
            command:
            - /usr/bin/container-startup
          failureThreshold: 10
          periodSeconds: 5
        ports:
        - containerPort: 5432
          name: psql
          protocol: TCP
        securityContext:
          privileged: false
      restartPolicy: Always
      schedulerName: default-scheduler
```

The working ingress.yml (with the TLS commented out):
- All the annotations are context that works for other containers, i.e. auth-tls... or attempts to correct the above problem. Note all have been commented out as it is the spec.tls...  section that breaks. 
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    # kubernetes.io/ingress.class: "nginx"
    # nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
    # nginx.ingress.kubernetes.io/auth-tls-secret: "data/ca-certs"
    # nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
    # nginx.ingress.kubernetes.io/auth-tls-error-page: "https://youtu.be/t3otBjVZzT0"
    # nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "false"
    
    # nginx.ingress.kubernetes.io/enable-cors: "false"
    # nginx.ingress.kubernetes.io/cors-allow-origin: "https://psql.gautier.org/"
    # nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    
    # nginx.ingress.kubernetes.io/ssl-redirect: "true"
    # nginx.ingress.kubernetes.io/hsts: "true"
    # nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    # nginx.ingress.kubernetes.io/preserve-trailing-slash: "true"
    
    # nginx.ingress.kubernetes.io/http2-push-preload: "true"
    
    # nginx.ingress.kubernetes.io/send_timeout: "3m"
    # nginx.ingress.kubernetes.io/proxy-connect-timeout: "3m"
    # nginx.ingress.kubernetes.io/proxy-read-timeout: "3m"
    # nginx.ingress.kubernetes.io/proxy-send-timeout: "3m"
    
    # nginx.ingress.kubernetes.io/add-base-url: "true"
    # nginx.ingress.kubernetes.io/rewrite-target: /
    # nginx.ingress.kubernetes.io/rewrite-target: /$1
  namespace: data
  name: pgweb
spec:
#  tls:
#   - hosts:
#       - psql.gautier.org
  ingressClassName: public
  rules:
  - host: psql.gautier.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pgweb
            port:
              number: 8080
```
