### ISSUE TITLE
role "pgweb" does not exist

### ISSUE THREAD

**Issue by bobbymannino** [sosedoff/pgweb#767]
whenever I run the docker image (compose) I always get this error `FATAL:  role "pgweb" does not exist` from the `database` container and `Error: connection refused` from the `pgweb` container, im not sure if its something to do with me? should I add the role? The Postgres instance works fine so im not sure what it is.

my docker compose is as follows;

```yml
services:
  database:
    container_name: fma-db
    image: postgres:17-alpine
    restart: always
    ports:
      - "2212:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=fma
    healthcheck:
      test: pg_isready -U pgweb -h 127.0.0.1
      interval: 5s

  pgweb:
    container_name: pgweb
    restart: always
    image: sosedoff/pgweb
    ports:
      - "8081:8081"
    environment:
      - PGWEB_DATABASE_URL=postgres://postgres:postgres@127.0.0.1:2212/fma?sslmode=disable
    networks:
      - pgweb
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "nc", "-vz", "127.0.0.1", "8081"]
      interval: 5s
    links:
      - database:database

volumes:
  db:

networks:
  pgweb:
```
