### ISSUE TITLE
could not see bookmark

### ISSUE THREAD

**Issue by Eric-zch** [sosedoff/pgweb#784]
I built a ppc64 docker image based on the code in pgweb and deployed it to Openshift ppc64le with 

1. create a configmap for bookmarks
```
oc create configmap pgweb-bookmarks \
  --from-file=db1.txt \
  --from-file=db2.txt \
  --from-file=db2.txt
```
2. create deployment and service
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgweb
  labels:
    app: pgweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgweb
  template:
    metadata:
      labels:
        app: pgweb
    spec:
      containers:
      - name: pgweb
        image: pgweb:0.16.2
        args: ["--bookmarks-dir=/bookmarks"]
        volumeMounts:
        - name: bookmarks
          mountPath: /bookmarks
        ports:
        - containerPort: 8081
        readinessProbe:
          httpGet:
            path: /
            port: 8081
        env:
        - name: PGWEB_SESSIONS
          value: "1"
      volumes:
      - name: bookmarks
        configMap:
          name: pgweb-bookmarks
---
apiVersion: v1
kind: Service
metadata:
  name: pgweb
  labels:
    app: pgweb
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app: pgweb
  type: ClusterIP
```
I could not see bookmark after the pod is started, there is no error messages.
