### ISSUE TITLE
Make port in the official Docker image configurable

### ISSUE THREAD

**Issue by dzikoysk** [sosedoff/pgweb#787]
Right now, the official image only allows us to start the web service on port ::8081:

* https://github.com/sosedoff/pgweb/blob/8413681db02784096087d093697e0a12ea2e3114/Dockerfile#L48

It'd be great if that port could be defined via environment variable. If we're running a bunch of services on the same network, it's pretty easy to have a conflict between services (or even across the same instances of pgweb for different databases).

**Comment by sosedoff** [comment]
@dzikoysk How are you running these multiple instances of Pgweb? With Docker you can remap ports however you'd like, same goes for k8s so i'm not entirely sure why you're running into this port collision issue. Appreciate the suggestion though.

**Comment by dzikoysk** [comment]
That's true, the port remap works, but only for the external host, but inside the Docker network, these services are actually running on the actual ports. Let's say we have this Docker compose:

```
services:
  postgres-ui-1
      container_name: postgres-ui-1
      image: sosedoff/pgweb:latest
      restart: always
      ports:
        - '10001:8081'
      networks:
        - same
   postgres-ui-2:
      container_name: postgres-ui-2
      image: sosedoff/pgweb:latest
      restart: always
      ports:
        - '10002:8081'
      networks:
        - same
  
networks:
  same:
    driver: bridge
 ```

If I'd try to visit these services from the host network, then of course both of them are running at ::10001 and ::10002.
But if you'd try to access them by some other service running in the container, then it becomes a little bit more tricky, because their addresses are `http://postgres-ui-1:8081/` and `http://postgres-ui-2:8081/`. When does it matter? For instance when you're also running all of that via a proxy (like Nginx), so you need to address all of your services within the internal network. I mean - it still works, but it's less than desired. I assume that instead of names, some people may also use generic `0.0.0.0`, but idk how it'd behave in this case, because I never tried it.
